sudo: required
dist: trusty
group: deprecated-2017Q4
language: csharp
solution: ExpediaInterview.sln
mono: none
dotnet: 2.1.2
script:
- dotnet restore
- cd ExpediaInterviewUnitTests
- dotnet test
deploy:
  provider: heroku
  buildpack: "https://github.com/jincod/dotnetcore-buildpack"
  api_key:
    secure: F8ogCvRSzL0LcxVbRJ/4OYGdPG/1vdXd48C3eeLK0LQXN39twTfBaoaQ8YwAHM+0SPcK4VpZASkDXJKoAAAs/XKdyPlq/lYci0vh/OwiynoMKS1bn83It5/1lwJujclxROS3oSAHD3E16X9lK49+IIdkVE5q8kgs/6GXpeqWlmnBzxIL8pV0s1UJqadJNEdvXaxG55CLwpAG+TdRjGxGeZvIdmgq+LgPS7125Ce0+uNBU0rL5pyAys4wFMayryhg2EhA/Y0U5reZeb3uZmwhaeHhfzZAyvCpSDZLirf/OGcwZa5+HJ0O+mthi+eY2iI/9LYt/nZ0LJsLO5vPxCSt4zaXoYTQ1Zi7gClCOfIMPGbw8ktPO8jTcEmcpbZWSVzO2Gb+0IFW8LCYJbWxkPNRSBB9Id8rJ4WZVCPz590dLUUEO+/G/wNX8nOg9ksm/kb+kLGEqJjenoBkKRyeBUip8YwIJs0v2MZ0IC3gYWw2jeChrAvwAx9xfmuuhC3KVlQNvI5M7xNiGH0SLlWOuyQoiNlY+CRSZ+JoGKYEd8n6JdlLkoBClKQS4/cTtP8DAqwEbiN6GrT169H4Qdi64u9o74et9xypCNXo8daWevGKe6kxCPl3y6bZZxFGi7AvxP9WF/V0FQafkSr2kAQLfEFNX6JT9VMWUKUBXpvLcy9efyQ=
  app: xpdealsfinder
  strategy: git
  skip_cleanup: true
  on:
    repo: a-ayyash/xpdealfinder
repo: a-ayyash/xpdealfinder
