sudo: required
dist: trusty
group: deprecated-2017Q4
language: csharp
solution: ExpediaInterview.sln
mono: none
dotnet: 2.1.2
script:
- dotnet restore
- cd ExpediaInterviewUnitTests
- dotnet test
deploy:
  provider: heroku
  buildpack: "https://github.com/jincod/dotnetcore-buildpack"
  api_key:
    secure: DdSeJNCePp+O9srer4/7FG4ViJkeaC5f2aKlXjUNtyvXJ91PUvenbsCSo8BkZw4xVILIgJmGZqTwrprQePt8o6/mbMxFBHJgxVt8kGmEbwOL5vlWE1q2Vs1Dr3fiU1ZjBRfrN5PetnCYhI5JCqaKedV+NYMP/gZhtzXIL/09m2qOxTc7jua68dsnzbuLnvN30F6Gn9eLUHpl4SKqnndXhmEQjpCQJik5sYXBsZX04pSw+v3/0sJXgT77xoiMG1VrG28xY+/WVKliS+E6lwoXtdkbfngH/qjHsTMPYKJ3DHEAo3m+QYIR4q/Sh8amQoMqsxl5O/GW1AqiPwPa76c83gJk1mDc4Koea1Eyou3fKoTf3bUuWopR71In/f10I3QHHdXuNxqb12yyFt62SW4uPD0r6zTYkNkIIg+pkWIlJZN7heXfxIaPEuTcmnOdjlHx8lZs3J463xqrFYU9A8mQdrT7SMALiQvmQ8xXroBaYwsOmXOgcsbp+qznD2+yzDufPUb2/PZ/6T3ObiVxLzn6laO8TPppMRSdRmWRs3yCGf252bgqLmyNoVrfbPlC7dW1J5M0w5cs9BgXdDq9YOwBXCCwDw979rG7PIMhrbGNOPkBV0pd32sP4nCIY66HI4C41/kdOEIuRORybyhRTkirvGbYxDElQlFUnHvLlrrJBoc=
  app: expediainterview
  strategy: git
  skip_cleanup: true
  on:
    repo: a-ayyash/ExpediaInterview
